// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: hello.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "";

export interface HelloRq {
  name: string;
}

export interface HelloRs {
  greeting: string;
}

function createBaseHelloRq(): HelloRq {
  return { name: "" };
}

export const HelloRq: MessageFns<HelloRq> = {
  encode(message: HelloRq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HelloRq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHelloRq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HelloRq {
    return { name: isSet(object.name) ? globalThis.String(object.name) : "" };
  },

  toJSON(message: HelloRq): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HelloRq>, I>>(base?: I): HelloRq {
    return HelloRq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HelloRq>, I>>(object: I): HelloRq {
    const message = createBaseHelloRq();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseHelloRs(): HelloRs {
  return { greeting: "" };
}

export const HelloRs: MessageFns<HelloRs> = {
  encode(message: HelloRs, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.greeting !== "") {
      writer.uint32(10).string(message.greeting);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HelloRs {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHelloRs();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.greeting = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HelloRs {
    return { greeting: isSet(object.greeting) ? globalThis.String(object.greeting) : "" };
  },

  toJSON(message: HelloRs): unknown {
    const obj: any = {};
    if (message.greeting !== "") {
      obj.greeting = message.greeting;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HelloRs>, I>>(base?: I): HelloRs {
    return HelloRs.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HelloRs>, I>>(object: I): HelloRs {
    const message = createBaseHelloRs();
    message.greeting = object.greeting ?? "";
    return message;
  },
};

export type HelloService = typeof HelloService;
export const HelloService = {
  helloWho: {
    path: "/Hello/helloWho",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: HelloRq) => Buffer.from(HelloRq.encode(value).finish()),
    requestDeserialize: (value: Buffer) => HelloRq.decode(value),
    responseSerialize: (value: HelloRs) => Buffer.from(HelloRs.encode(value).finish()),
    responseDeserialize: (value: Buffer) => HelloRs.decode(value),
  },
} as const;

export interface HelloServer extends UntypedServiceImplementation {
  helloWho: handleUnaryCall<HelloRq, HelloRs>;
}

export interface HelloClient extends Client {
  helloWho(request: HelloRq, callback: (error: ServiceError | null, response: HelloRs) => void): ClientUnaryCall;
  helloWho(
    request: HelloRq,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HelloRs) => void,
  ): ClientUnaryCall;
  helloWho(
    request: HelloRq,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HelloRs) => void,
  ): ClientUnaryCall;
}

export const HelloClient = makeGenericClientConstructor(HelloService, "Hello") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): HelloClient;
  service: typeof HelloService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
